### PR TITLE
Added reporting and moved a few things around

### PR DESCRIPTION
**Pull request by johnhidey**
You will need to have grunt-cli installed globally

`npm install grunt-cli -g`

after that make sure that you have all the dependencies that are needed by doing a 

`npm install`

then run your tests.  When tests finishes, it will create a folder in the tests/reports folder which in there is an html page.  Open that page to view your report.  

Enjoy

### CODE REVIEW

**Comment by johnhidey** [comment]
@bulldiser The pull-request is ready to go now.  You need to make sure that you have gulp and grunt-cli installed globally

```
npm install gulp -g
npm install grunt-cli -g
```

There are now two tasks in your gulp file.  
* test
* report

`gulp test` will invoke the tests that are in the tests directory.  After this, the task is complete
`gulp report` has a dependency on test which will invoke the tests first, then after the tests are complete the report will be built.

The `tests/reports` folder will contain all the reports from all the different times that `gulp report` is run.  If you want to run tests but not have a report show in the archive, just run `gulp test`

Enjoy

**Comment by bulldiser** [comment]
I've started testing your pull request on my machine. I'm getting an error message that I'm looking into in:

[18:28:50] 
node.js:673
          throw new Error('Implement me. Unknown stdin file type!');
                ^
Error: Implement me. Unknown stdin file type!
    at process.stdin (node.js:673:17)
    at async.eachSeries.self.emit.gutil.PluginError.plugin (C:\Users\diser\Documents\Visual Studio 2013\Projects\Rembrandt\NightwatchDemo\node_modules\gulp-shell\index.js:65:14)
    at C:\Users\diser\Documents\Visual Studio 2013\Projects\Rembrandt\NightwatchDemo\node_modules\gulp-shell\node_modules\async\lib\async.js:162:20
    at iterate (C:\Users\diser\Documents\Visual Studio 2013\Projects\Rembrandt\NightwatchDemo\node_modules\gulp-shell\node_modules\async\lib\async.js:256:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (C:\Users\diser\Documents\Visual Studio 2013\Projects\Rembrandt\NightwatchDemo\node_modules\gulp-shell\node_modules\async\lib\async.js:275:9)
    at Object.async.forEachSeries.async.eachSeries (C:\Users\diser\Documents\Visual Studio 2013\Projects\Rembrandt\NightwatchDemo\node_modules\gulp-shell\node_modules\async\lib\async.js:211:22)
    at DestroyableTransform._transform (C:\Users\diser\Documents\Visual Studio 2013\Projects\Rembrandt\NightwatchDemo\node_modules\gulp-shell\index.js:35:11)
    at DestroyableTransform.Transform._read (C:\Users\diser\Documents\Visual Studio 2013\Projects\Rembrandt\NightwatchDemo\node_modules\gulp-shell\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\Users\diser\Documents\Visual Studio 2013\Projects\Rembrandt\NightwatchDemo\node_modules\gulp-shell\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\Users\diser\Documents\Visual Studio 2013\Projects\Rembrandt\NightwatchDemo\node_modules\gulp-shell\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
Process terminated with code 8.

**Comment by bulldiser** [comment]
These reports are super groovy!

**Comment by bulldiser** [comment]
I got things working by forking gulp-shell and removing references to stdin.

**Pull request merged**
